### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by georgecm** [Intevel/nuxt-directus#109]
### Version

nuxt-directus: 3.2.2
nuxt: 3.0.0

### Steps to reproduce

Hi, I'm just trying to use this plugin and whatever I do I keep getting a CORS error on login. My server settings are fine and I can manually do the request with useFetch (/auth/login) with no issues.

Whenever I use the internal login function I get the error. Both locally and when deployed to a test machine.

> Access to fetch at 'https://domain/auth/login' from origin 'http://localhost:3000' has been blocked by CORS policy: Request header field authorization is not allowed by Access-Control-Allow-Headers in preflight response.

> POST https://domain/auth/login net::ERR_FAILED

I thought it was a server error but it's not...

**Comment by Intevel** [comment]
Why do you think this is no server error?

**Comment by georgecm** [comment]
Because I do the same request via nuxt fetch and it works fine. Also I have tested the cors restriction of the website using an online tester and it also works. Do you think it might me something else?

**Comment by georgecm** [comment]
@Intevel I guess it works for you and since this hasn't come up before, it seems not to be universal. I wonder if I need to add some specific config.

My config:

I do the requests from Netlify (domain.com)

My Nuxt 3.2 config is 

`directus: { 
      url: "https://some.domain.com",
      token: "static_token" },`
      
 Nothing else. 
 
 I only use the setup for login that is displayed in your tutorial 
 
```
 <script setup lang="ts">
const { login } = useDirectusAuth();
const router = useRouter();

const onSubmit = async () => {
  try {
    await login({ email: "email", password: "password" });
  } catch (e) {
    console.log(e)
  }
};
</script>
```

**Comment by Intevel** [comment]
Yeah but I can't really understand it. Nuxt Directus uses the Nuxt Fetch function.

**Comment by georgecm** [comment]
I know. I am just thinking if there is any header missing (?)

I had a look at this "https://github.com/becem-gharbi/nuxt-directus-auth" and it mentions that both client and server must be under the same domain. 

Any chance this is the same? It doesn't make sense to me, since splitting the backend and frontend is one of the reasons to use this architecture but just saying...

**Comment by Intevel** [comment]
@georgecm https://github.com/becem-gharbi/nuxt-directus-auth/blob/main/src/runtime/composables/useDirectusAuth.ts
https://github.com/becem-gharbi/nuxt-directus-auth/blob/main/src/runtime/composables/useDirectusFetch.ts

I don't see any headers in this module which `nuxt-directus` doesn't set. Except set-cookie which _should_ have nothing to do with CORS though.

@rijkvanzanten Do you have an idea? You are more familiar with the architecture of directus.

**Comment by georgecm** [comment]
@Intevel I managed to fix the issue.

Long story short, it was a server config issue (sorry for saying it was not originally but this working with a normal request confused me).

The missing piece was that I needed to allow the "authorization" header specifically, which was required by the prefetching request.

Maybe my server configuration was very strict (?) but I think it's good to document this for the setup of the module.

**Comment by Intevel** [comment]
> Long story short, it was a server config issue (sorry for saying it was not originally but this working with a normal request confused me).

No problem, im open to everything 💯 

> Maybe my server configuration was very strict (?) but I think it's good to document this for the setup of the module.

I will think about it, when refactoring docs
