### ISSUE TITLE
Token cookies are not set with an expire time

### ISSUE THREAD

**Issue by matt-clegg** [Intevel/nuxt-directus#131]
### Version

nuxt-directus v5.1.3
nuxt: v3.3.2

### Steps to reproduce

1. Clear your browser cookies for your copy of Directus.
2. Login to Directus.
3. Inspect the browser cookies, you will see the Expires / max age set:
![image](https://user-images.githubusercontent.com/34515355/233836385-c5f82079-465b-4b64-9879-508b08ad00e3.png)
4. Clear your browser cookies for your nuxt frontend site.
5. Login using the `useDirectusAuth()` module.
6. Inspect the browser cookies, the Expires / max age is set to Session:
![image](https://user-images.githubusercontent.com/34515355/233836463-36f5f249-df89-4bc9-8d27-83e9bd590a99.png)

### What is Expected?

Directus token cookies should have an Expires / max age property set.

### What is actually happening?

Directus token cookies have no Expires / max age property set, so nuxt will default those cookies to Session by default and are removed when the browser closes. See the maxAge / expires section of the useCookies nuxt docs [here](https://nuxt.com/docs/api/composables/use-cookie#maxage-expires).

**Comment by Intevel** [comment]
@matt-clegg This actually sounds right, but Nuxt removes cookies when the browser is closed, if the cookie has an maxAge or expires.

**Comment by Intevel** [comment]
Then I misunderstood, then we should implement that.

**Comment by matt-clegg** [comment]
No worries, that would be great if possible.
