### ISSUE TITLE
bug: data fetched doesn't correctly update dom

### ISSUE THREAD

**Issue by Sandros94** [Intevel/nuxt-directus#148]
I'm not fully sure where within Nuxt this problem happens. Essetially it looks like the virtualDOM doesn't use the entirety of the fetched data once the client is rendering.

I'm writing here just to rule out any possibility that `useDirectusItems` is the problem.

## Version

nuxt-directus v5.1 to latest
nuxt: v3.3 to latest

## Reproduction Link
I'm unable to share a full reprod link (yet), but I'll try to share as much code as possible:
### Nuxt - gallery.vue
```vue
<template>
    <ul v-for="link in links" :key="link">
        <li>
            <a :href="link.link" target="_blank" rel="noopener noreferrer">{{ link.event.name }} | {{ link.date  }}</a>
        </li>
    </ul>
</template>

<script setup scoped>
const { getItems } = useDirectusItems();
const links = await getItems({
    collection: "gallery_links",
    params: {
        fields: [
            "id",
            "date",
            "event.name",
            "link",
            "status"
        ],
        filter: {
            status: "visible",
        },
        sort: [
            "-date",
        ],
    }
});
};
```

### Directus
A `gallery_links` collection that has:
- `date`: single day picker
- `event`: M2O rel to an events collection (each event has a name, a desc and an image)
- `link`: string
- `status`: hidden, scheduled, visible

## Steps to reproduce
1. Populate the `gallery_links` collection with something like 4 links.
2. `npm run build` and once finished `npm run preview`.
3. navigate to the preview and you'll see the 4 links.
4. open in a new tab directus and set one of the links (preferably not the last one) `status` to `hidden`.
5. reload the preview page and you'll see the hydration taking place soon after.

## What is Expected?
All `link.link`, `link.event.name` and `link.date` should correctly update.

## What is actually happening?
The link after the hidden one, although it has the correct `link.event.name` and `link.date` it will have the wrong `link.link` (to be precise it will have the link from the hidden one).

## Additional info
I made sure multiple times that my Directus instance isn't causing the problem, and verified via various tools like hoppscotch.
(Directus cache is flushed at every collection update).

**Comment by Sandros94** [comment]
I was building a reproduction to be shared, but I'm having an hard time making it to reproduce on that, I'm more and more thinking is a timing related issue on nuxt side, but I have no experience in how to analyze this.

Moreover the reprod doesn't appear to have any problem in updating the html code on server side, so it must be that in the project I'm facing this problem has something to do with it.

Closing for now, until fully reproduceable, to clean up things.

**Comment by Intevel** [comment]
Maybe you should create an issue at nuxt.

/cc @danielroe

**Comment by danielroe** [comment]
You shouldn't update the 'state' used to render the DOM while hydrating the app. So fetching _new_ data that is different from the data used to produce the rendered HTML will not work.

Instead, you can wrap the whole thing in `useAsyncData` (and Nuxt will ensure the payload is passed from server -> client) and then call `refresh` to get up-to-date data after your app is hydrated - you can use `onNuxtReady` for this...

**Comment by Sandros94** [comment]
>You shouldn't update the 'state' used to render the DOM while hydrating a server-rendered app. So fetching new data that is different from the data used to produce the rendered HTML will not work. (That is, it will cause hydration issues, or partially update the DOM.)
>
>Instead, you can wrap the whole thing in useAsyncData (and Nuxt will ensure the payload is passed from server -> client) and then call refresh to get up-to-date data after your app is hydrated - you can use onNuxtReady for this...

Thanks for the info and rereading the nuxt docs is making me think of a few improvements on my end. And potentially nuxt-directus too, but first I want to be sure to have understood things correctly:

So if I correctly followed you along my code should become something like this (plus styling just for the sake of it):
```vue
<template>
    <div>
        <UContainer class="w-full max-w-8xl px-8 prose dark:prose-invert">
            <UButton label="Refresh" :loading="pending" @click="refreshData"/>
            <ul v-for="link in links" :key="link">
                <li>
                    <a :href="link.link" target="_blank" rel="noopener noreferrer">{{ link.name }} | {{ link.date  }}</a>
                </li>
            </ul>
        </UContainer>
    </div>
</template>

<script setup scoped>
const { data: links, pending, refresh } = useAsyncData(async () => {
    const { getItems } = useDirectusItems()
    return await getItems({
        collection: 'links',
        params: {
            fields: ['id', 'name', 'link', 'date', 'status'],
            filter: {
                status: 'visible',
            },
            sort: ['-date'],
        },
    })
})

const refreshData = () => {
    refresh()
}

onNuxtReady(() => {
    refreshData()
})
</script>
```

What I don't yet understand is the need for `onNuxtReady`:
Doesn't `useAsyncData` fetches the latest data on page request? Or is `onNuxtReady` just a way to double check if there is newer data available since last server side fetch?

Moreover:
When I trigger a manual refresh with a button, the data fetch is done client side or server side? I imagine the latter, but then how could I handle SSG in other projects?

**Comment by danielroe** [comment]
It depends if you always want up-to-date info. If not, then you should not call `refresh` as it will _force_ an extra API call.

**Comment by Sandros94** [comment]
So, I studied and tested a little more and indeed it was an hydration issue and it was only updating the DOM partially. (I'm updating the status of this issue accordingly)

---
>It depends if you always want up-to-date info. If not, then you should not call `refresh` as it will _force_ an extra API call.

Makes sense.

Could I ask you one last bite of your knowledge?
Lets say I'm on ssr with a custom dockerfile/helm deployment of my node, on a really small vps. This means that for performance reason I wouldn't like to fully rebuild nuxt, but still I need to periodically update the server-side html (seo reasons).
Is there a way to somewhat invalidate (via timer) that server-side html? So that nuxt could update it.

I'm not sure if I'm looking at the right docs:
- [Nuxt - Rendering Modes](https://nuxt.com/docs/guide/concepts/rendering#hybrid-rendering)
- [Nitro - Cache Route Rules](https://nitro.unjs.io/guide/cache#route-rules)

### Use case
1. Nuxt gets rebuilt monthly or every 2 months.
2. Once/Twice a week a news gets published via directus api. (SEO is needed)
3. For the following minutes/hours after the news was published there might be updates. (SEO not strictly needed but welcome).

**Comment by danielroe** [comment]
@Sandros94 You can use the `swr` route rule to handle caching/updating HTML periodically. This works if you do not prerender the pages.
