### ISSUE TITLE
Error after upgrade 5.4.0

### ISSUE THREAD

**Issue by paulvonber** [Intevel/nuxt-directus#154]
nuxt-directus: 5.4.0
nuxt: 3.5.3

After upgrading to 5.4.0 getting an error, computed is not defined:
<img width="1121" alt="image" src="https://github.com/Intevel/nuxt-directus/assets/37245111/6c167cfb-d763-484b-8a92-e39e941a9b92">

**Comment by casualmatt** [comment]
The bug is already solved; waiting for a new patch release. 
[65c1cdf](https://github.com/Intevel/nuxt-directus/commit/65c1cdfaaabbf84d74fbb3ab68f492949f657ea9#comments)
