### ISSUE TITLE
When updating to 5.4.0 and 5.4.1, nuxt startup crashes!

### ISSUE THREAD

**Issue by leosin** [Intevel/nuxt-directus#156]
When updating to 5.4.0 and 5.4.1, nuxt startup crashes!

```
nuxt.js?v=1cab7ca8:94  
[nuxt] error caught during app initialization ReferenceError: useDirectusUrl is not defined
```

### Version
nuxt-directus :5.4.1
nuxt: 3.5.2

**Comment by Intevel** [comment]
Fixed with v5.4.2

**Comment by leosin** [comment]
up to 5.4.2, a new error tip :
```
nuxt.js?v=e48f5f39:94  [nuxt] error caught during app initialization ReferenceError: useRoute is not defined
```

**Comment by Intevel** [comment]
I dont have this Issue when I start 🗡️ Thats funny. It looks like that the implementation of the RFC was broken.

**Comment by leosin** [comment]
ok i'll test it later

**Comment by Intevel** [comment]
I see the issue, and will fix it.

**Comment by Intevel** [comment]
Fixed @leosin

**Comment by leosin** [comment]
perfect now 👍
