### ISSUE TITLE
bug: v5.4.3 'token_expired' always 'true'.

### ISSUE THREAD

**Issue by nilswinking** [Intevel/nuxt-directus#157]
### Version

nuxt-directus v5.4.3
nuxt: 3.5.2

### Steps to reproduce

Create a login page with the following content:

```
<template>
  <div>
    <div>
      <form @submit.prevent="onSubmit">
        <input type="text" name="email" placeholder="user@example.com" v-model="email">
        <input type="password" name="password" placeholder="password" v-model="password">
        <button @submit.prevent="onSubmit">Login</button>
      </form>
    </div>
  </div>
</template>

<script setup lang="ts">

const {login} = useDirectusAuth();

const email = useState<string>('email', () => '')
const password = useState<string>('password', () => '')

const onSubmit = async () => {
  try {
    console.log()
    await login({email: email.value, password: password.value});
  } catch (e) {
  }
};
</script>

```

(Config only contains the directus url)

Enter login details and click login.

### What is Expected?

Login works and the user object is successfully fetched

### What is actually happening?

Login request works correctly, access token and refresh token are returned and cookies are set. However the request to fetch the user fails with a `401`. No cookies and no bearer token are send on the request.

**Comment by casualmatt** [comment]
Hello @nilswinking, 
I succeed in replicating your bug, it's relative to the token expire function that is used inside the module, I will take a look tomorrow at how we can fix it. 

But for now, I would suggest using [v5.3.0](https://github.com/Intevel/nuxt-directus/releases/tag/v5.3.0) which is our stable version.

**Comment by nilswinking** [comment]
Thanks for the quick fix!

**Comment by casualmatt** [comment]
It was a big PR that we merge and it have small changes to the core code of the module, which have given consequences everywhere.
