### ISSUE TITLE
Can't log in 

### ISSUE THREAD

**Issue by adamkhan** [Intevel/nuxt-directus#164]
Hi,

The module is returning "INVALID_PROVIDER" when I try to log in.

Directus's .env file has the following:

AUTH_LOCAL_DRIVER="local"
AUTH_PROVIDERS="local"

Should this work? Or does nuxt-directus require a different setup?

**Comment by Intevel** [comment]
How do you try to login with nuxt-directus?

**Comment by adamkhan** [comment]
Hi, thanks for replying. I'm following the docs at https://nuxt-directus.netlify.app/composables/usedirectusauth. From my component:

`<template>

<div class="_login-register" >

	<div
		class="_login-register-fields"
	>

		<input 
			type="email" 
			class="-person" 
			v-model="login.email" 
			placeholder="Email" 
			@keyup="clearMessage"
		/>

		<input 
			:ref="'password-input'"
			:type="passwordType" 
			class="-person" 
			v-model="login.password"
			placeholder="Password" 
			@keyup="clearMessage"
		/>

	</div>

	<div
		class="_login-register-buttons"
	>

		<div 
			class="
				_login-holder 
				-button-holder
			"
		>
			<button 
				@click.stop="directusLogin" 
				type="submit"
			>
				Log in
			</button>
		</div>
	</div>


</div>

</template>


<script setup lang="ts">

const { login } = useDirectusAuth();
const router = useRouter();

const directusLogin = async () => {

	try {
		await login({ 
			email: login.email, 
			password: login.password 
		});  
		console.log("logged in!");

	} catch (e) {
		console.log("failed to log in");
		console.log(e);
  	}
};

</script>`

**Comment by adamkhan** [comment]
Hope you can help me with this, I'm still not able to get logging in working. Hopefully I'm just missing a simple setting. What exactly do we need in the directus directive in nuxt.config.ts? In the .env file for Directus? Any particular settings for the User Role in Directus?

**Comment by Intevel** [comment]
I will try to reproduce this later 👍🏼

**Comment by adamkhan** [comment]
Thanks! FYI, in nuxt.config.ts I have:

```directus: {
	url: "http://localhost:8055",
},```

And in the Directus log on the Terminal I'm getting:

POST /auth/login 403

**Comment by adamkhan** [comment]
After enabling debug mode in Directus logging and got the following:

```
DEBUG: Invalid provider.
    err: {
      "type": "",
      "message": "Invalid provider.",
      "stack":
          DirectusError: Invalid provider.
              at AuthenticationService.login ([path]/directus/node_modules/@directus/api/dist/services/authentication.js:89:19)
              at async [path]/directus/node_modules/@directus/api/dist/auth/drivers/local.js:69:56
      "name": "DirectusError",
      "code": "INVALID_PROVIDER",
      "status": 403
    }
```

**Comment by adamkhan** [comment]
More investigations: looking at node_modules/@directus/api/dist/auth/drivers/local.js, I see that the provider is "default" not local. If I change it in there to local, my error changes from "invalid provider" to:

```
DEBUG: Invalid user credentials.
    err: {
      "type": "",
      "message": "Invalid user credentials.",
      "stack":
          DirectusError: Invalid user credentials.
              at LocalAuthDriver.verify ([path]/directus/node_modules/@directus/api/dist/auth/drivers/local.js:31:19)
              at async LocalAuthDriver.login ([path]directus/node_modules/@directus/api/dist/auth/drivers/local.js:35:9)
              at async AuthenticationService.login ([path]/directus/node_modules/@directus/api/dist/services/authentication.js:111:13)
              at async [path]/directus/node_modules/@directus/api/dist/auth/drivers/local.js:78:56
      "name": "DirectusError",
      "code": "INVALID_CREDENTIALS",
      "status": 401
    }
```

Although the credentials are fine.

**Comment by adamkhan** [comment]
Well it works if I log in as the Directus admin, which uses the **default** provider, but **local** provider still does not work. So I changed all the user accounts to have **default** instead of **local** as their provider, but login still does not work for them.

**Comment by Intevel** [comment]
> More investigations: looking at **node_modules/@directus/api/dist/auth/drivers/local.js**, I see that the provider is "default" not "local". If I manually change it in there to local, my error changes from "invalid provider" to:
> 
> ```
> DEBUG: Invalid user credentials.
>     err: {
>       "type": "",
>       "message": "Invalid user credentials.",
>       "stack":
>           DirectusError: Invalid user credentials.
>               at LocalAuthDriver.verify ([path]/directus/node_modules/@directus/api/dist/auth/drivers/local.js:31:19)
>               at async LocalAuthDriver.login ([path]directus/node_modules/@directus/api/dist/auth/drivers/local.js:35:9)
>               at async AuthenticationService.login ([path]/directus/node_modules/@directus/api/dist/services/authentication.js:111:13)
>               at async [path]/directus/node_modules/@directus/api/dist/auth/drivers/local.js:78:56
>       "name": "DirectusError",
>       "code": "INVALID_CREDENTIALS",
>       "status": 401
>     }
> ```
> 
> even though the credentials are fine.

Nuxt Directus does not use the directus SDK.

**Comment by adamkhan** [comment]
I've narrowed the issue down to the following: in Directus's .env file, if AUTH_DISABLE_DEFAULT="true" then it always uses the "default" login method, even though all the users are registered using "local" so fails (I reverted them back to "local"). But if I set AUTH_DISABLE_DEFAULT="false" then I get:

`DirectusError: Route /auth/login doesn't exist.`

Does this help clarify what might be going wrong?

**Comment by adamkhan** [comment]
OK, I fixed this, I think you can close it. The issue it turns out was particular to my situation.

I had imported my users from a different system to Directus, which did not use argon2 as the hashing mechanism for passwords, so the argon2-based password verification in the local authentication driver was failing.
