### ISSUE TITLE
useDirectusAuth creates warning when used in middleware

### ISSUE THREAD

**Issue by Dominic-Marcelino** [Intevel/nuxt-directus#167]
When using useDirectusAuth() in a midleware, nuxt warns about the usage of `useRoute` in a middleware.

As the route is only needed for the `loginWithProvider()` function, I'd suggest to move the `const route = useRoute()` into the desired function.

https://github.com/Intevel/nuxt-directus/blob/126e7d1ac579f6c7fc954eaf7d74ed4de68a5311/src/runtime/composables/useDirectusAuth.ts#L24

### Version

nuxt-directus 5.4.4
nuxt: 3.6.1

### Steps to reproduce
- Use `useDirectusAuth ` auth in a middleware

### What is Expected?
- No warning

### What is actually happening?
Nuxt throws a warning:

> [nuxt] Calling `useRoute` within middleware may lead to misleading results. Instead, use the (to, from) arguments passed to the middleware to access the new and old routes.

**Comment by Intevel** [comment]
Fixed in newest Commit
