### ISSUE TITLE
user is undefined in middleware

### ISSUE THREAD

**Issue by creazy231** [Intevel/nuxt-directus#168]
As the title says: If you want to get the user inside a middleware using `const user = useDirectusUser();` the user object is not defined.

Workaround: Use `const { fetchUser } = useDirectusAuth();` to fetch the user if user from `const user = useDirectusUser();` is undefined.

### Version

nuxt-directus:  5.4.4
nuxt: 3.6.1

### What is Expected?
The user object

**Comment by Intevel** [comment]
That's not a bug, surely you should fetch the user if it's undefined.

**Comment by creazy231** [comment]
All right, so wouldn't it be cool to have a feature that fetches the user automatically whenever its requested but is undefined then?

**Comment by casualmatt** [comment]
Documentation needs to be updated with this example:

```ts
export default defineNuxtRouteMiddleware(async (to, _from) => {
  const { fetchUser, setUser } = useDirectusAuth();
  const user = useDirectusUser();
  if (!user.value) {
    const user = await fetchUser();
    setUser(user.value);
  }
  if (!user.value) {
    return navigateTo("/login");
  }
});
```

**Comment by Intevel** [comment]
Updated the documentation
