### ISSUE TITLE
Creating a new User

### ISSUE THREAD

**Issue by McSundae** [Intevel/nuxt-directus#171]
I'm currently working on an app with user authentification. Login already works but i got a problem with the createUser function.

I'm calling the function like this:

The transmitted data is:
{email: "admin@florian-strasser.de", password: "jyTraz-pujso3-hujqim", role: "cca0e78b-2d47-41c3-b65d-ae6d295615d5"}

const user = await createUsers({
      email: email,
      password: password,
      role: role.value.id,
});

Function is beeing executed and delivers always following error:
{message: "Invalid user credentials.", extensions: {code: "INVALID_CREDENTIALS"}}

I'm wondering what i'm doing wrong. Do i need to hash the password for example?

**Comment by McSundae** [comment]
My nuxt config looks like this:
css: [
    '~/assets/css/main.css'
],
modules: [
    '@nuxtjs/tailwindcss',
    'nuxt-directus'
],
directus: {
    url: 'https://directus.xyz.de/',
    token: 'lnpZ3BRCXWz7e1yk4bD3U6zsLz2KoTD8',
}

The User with this token has the rights to create users

**Comment by McSundae** [comment]
Okay... Seems like i'm totally stupid and this case can be closed.

I actually reset the generated token and edited this on the nuxt config and voila, everything works. Thanks alot @casualmatt - you pointed me in the right direction. I thought the "INVALID CREDENTIALS" meant the data i submitted was wrong

**Comment by casualmatt** [comment]
Np, 
I would suggest any way to move the URL to `runtimeConfig`, like that:
```typescript
  runtimeConfig: {
    public: {
      directus: {
        url: 'https://directus.xyz.de/',
      },
    },
  },
```
