### ISSUE TITLE
loginWithProvider(): ReferenceError: navigateTo is not defined

### ISSUE THREAD

**Issue by Colmea** [Intevel/nuxt-directus#175]
Hello,

First, thank you for your library, very useful !
Unfortunately, I cannot use the loginWithProvider() because it throws an errror with the navigateTo function.

### Version

nuxt-directus 5.4.4
nuxt: v3.6.3

### Reproduction Link

It's a fresh new Nuxt + nuxt-directus project. With a single file:
```
// app.vue
<script setup lang="ts">
const { loginWithProvider } = useDirectusAuth();
</script>

<template>
  <div>
    <button style="margin-top: 25px" @click="loginWithProvider('discord')">
      Login with OAuth
    </button>
  </div>
</template>
```

### Steps to reproduce

- use `loginWithProvider()`

### What is Expected?

No error

### What is actually happening?

An error is thrown:
```
Uncaught (in promise) ReferenceError: navigateTo is not defined
    at Proxy.loginWithProvider (useDirectusAuth.mjs:77:5)
```

Note that I can use all other hooks provided by nuxt-provider (even the basic login() function).
The error only happens with loginWithProvider()

Thank you for your help :) !

**Comment by casualmatt** [comment]
Hello @Colmea, 
Can you please send a stackblitz? it will make it easier to debug. 
[Here is a Nuxt template.](https://stackblitz.com/github/nuxt/starter/tree/v3/?file=README.md)

**Comment by Intevel** [comment]
I can reproduce this bug, will be fixed in the newest release.

**Comment by Intevel** [comment]
Fixed in 5549ccc

**Comment by Colmea** [comment]
Wow, that was fast.

I confirm everything works well now, thanks !

**Comment by cory-glooh** [comment]
My bad! damn nuxt auto-importing hid the error from me in vscode :D
