### ISSUE TITLE
expires is not a function

### ISSUE THREAD

**Issue by drennvinn** [Intevel/nuxt-directus#176]
it seems to be an error in the doc:

![Capture d’écran 2023-07-30 à 19 16 32](https://github.com/Intevel/nuxt-directus/assets/18407632/190df3a5-757c-4fe8-a78f-ef9b1e7dd28c)

it must be modified with `console.log(expires.value);`

**Comment by Intevel** [comment]
@drennvinn Thank you, feel free to create PR to change this in the documentation ;)
