### ISSUE TITLE
Add examples to documentation

### ISSUE THREAD

**Issue by Intevel** [Intevel/nuxt-directus#18]
https://github.com/directus/examples/tree/main/nuxt3/

**Comment by casualmatt** [comment]
I can take care of this this weekend.

**Comment by Intevel** [comment]
That would be great 💚

**Comment by casualmatt** [comment]
@Intevel any advice on what to add, or what you would like to see is appreciated.

An option is to add under  the "community " section a guide on how to read/use the boilerplate.

**Comment by Intevel** [comment]
@casualmatt that's a good suggestion. If you want you can implement that, currently I'm happy with the guide from me in the Directus blog there. In the future we can implement more guides from the community there.
