### ISSUE TITLE
"autoRefresh" option default value is false instead of true

### ISSUE THREAD

**Issue by nipakke** [Intevel/nuxt-directus#180]
### Version

nuxt-directus: v5.5.0

### Problem

The documentation states that the module option "autoRefresh" defaults to "true" but in the module definition the default is "false".
I don't know which one is the correct one but it confused me for a while.

Docs:

![image](https://github.com/Intevel/nuxt-directus/assets/66799869/26578912-2095-4645-8b0b-0285c3004433)

[Code](https://github.com/Intevel/nuxt-directus/blob/dd87663104b8e26ecbba4319c2b0423d3f2bba26/src/module.ts#L82C12-L82C12)

![image](https://github.com/Intevel/nuxt-directus/assets/66799869/7c49c3ec-5b65-4f28-9307-32c7b74c3ffc)

**Comment by Intevel** [comment]
Thanks! Updated the docs.
