### ISSUE TITLE
How to rename directus_token_expired_at

### ISSUE THREAD

**Issue by 53RG1005** [Intevel/nuxt-directus#207]
How to rename cookie directus_token_expired_at ?

**Comment by 53RG1005** [comment]
Project alive?

**Comment by 53RG1005** [comment]
@Intevel [src/runtime/composables/useDirectusToken.ts](https://github.com/Intevel/nuxt-directus/blob/bfa49b9862ba09c2eabbdb8c27c04b3e163e05e5/src/runtime/composables/useDirectusToken.ts#L40)

Add please ability to change expires cookie name :)

**Comment by casualmatt** [comment]
Hello @53RG1005, 
Can you give us more context on what could be helpful or how it's creating an issue/bug with the current implementation?

**Comment by casualmatt** [comment]
Currently, we are in the process of changing the core of the module to the new SDK. 
So we don't plan to add any additional features.
