### ISSUE TITLE
global query "deep" non supported

### ISSUE THREAD

**Issue by casualmatt** [Intevel/nuxt-directus#21]
### Version

nuxt-directus 1.5.0
nuxt: v3.0.0-27491748.3186841 

### Reproduction Link

If you pass those parameters to the SDK, it will not stringify the [deep](https://docs.directus.io/reference/query/#deep), but only the filter. 
```ts
fields:[
  "*",
  "invoices.number",
  "invoices.id",
  "invoices.total",
  "invoices.hosted_invoice_url",
  "invoices.status",
  "subscriptions.id",
  "subscriptions.status",
  "subscriptions.metadata_title"
],
deep:[
  {
    "invoices":{
      "_limit":3,
      "_sort":"-created",
    }
  }
]
```

### What is Expected?
that all the Global Query Parameters are supported, because i think that [Aggregation & Grouping](Aggregation & Grouping) could have the same issue been a complicated object. 

### What is actually happening?

The call made to the server have `deep=[object+Object]` as one of his parameters.

**Comment by casualmatt** [comment]
probably it just need to be added an other if for deep and maybe one for the aggregation and grouping. 
https://github.com/Intevel/nuxt-directus/blob/930ef94be39ed12fe211561d332af29ef3ca325a/src/runtime/composables/useDirectusItems.ts#L12-L15

**Comment by Intevel** [comment]
Thanks for your Issue @casualmatt. Fixed with the newest release 💚
