### ISSUE TITLE
Directus Websocket Support

### ISSUE THREAD

**Issue by Heartnett** [Intevel/nuxt-directus#214]
### Is your feature request related to a problem? Please describe.
Its a missing feature.

### Describe the solution you'd like
Websocket support.

### Describe alternatives you've considered
N/A

### Additional context
https://docs.directus.io/guides/real-time.html

**Comment by Heartnett** [comment]
@casualmatt thanks for the quick reply. Do you not want to keep this feature request open until its implemented?

**Comment by Sandros94** [comment]
> Do you not want to keep this feature request open until its implemented?

@casualmatt I do agree it could be helpful to keep this one open, since I have yet to doublecheck the latest fixes for both `ofetch` and `ws`

**Comment by casualmatt** [comment]
@Sandros94, maybe we create a feature/todo list on a discussion so that we track everything there.

**Comment by Sandros94** [comment]
> @Sandros94, maybe we create a feature/todo list on a discussion so that we track everything there.

Love the idea, doing it now

**Comment by casualmatt** [comment]
It's also good for me when I have to update the documentation.

**Comment by Sandros94** [comment]
Created at #215, @Heartnett feel free to comment for any additional information
