### ISSUE TITLE
Error: Cannot read properties of undefined (reading '_data')

### ISSUE THREAD

**Issue by hi-reeve** [Intevel/nuxt-directus#223]
### Version

nuxt-directus: 5.6.0
nuxt: 3.8.2

### Reproduction Link
https://github.com/hi-reeve/nuxt-directus-test

### Steps to reproduce
1. use nuxt-directus with asyncData
2. an error occured
3. set asyncdata option to `server:false`
4. data fetched

### What is Expected?
1. fetching data on serverside with no error

`nuxt.config.ts`
```ts
// https://nuxt.com/docs/api/configuration/nuxt-config

export default defineNuxtConfig({
    devtools: { enabled: true },
    runtimeConfig: {
        dbConnectionString: process.env.DIRECTUS_DIRECT_URL,
        directus: {
            url: process.env.DIRECTUS_APP_URL,
        },
    },
    modules: ["@nuxt/image", "@unocss/nuxt", "nuxt-directus"],
    imports: {
        dirs: ["libs/**", "composables/**"],
    },
    directus: {
        devtools: true,
        url: process.env.DIRECTUS_APP_URL,
        token: process.env.DIRECTUS_API_TOKEN,
    },
    experimental: {
        componentIslands: true,
        typedPages: true,
    },
});
```

the code
```vue
<script setup lang="ts">
import { type Blog } from "@/types/blog";

const { getItems } = useDirectusItems();
const {
    data: blogList,
    pending: loading,
    error,
} = await useAsyncData("bloglist", () =>
    getItems<Blog>({
        collection: "blog",
    })
);
const { data: blogListClient, pending: loadingClient } = await useAsyncData(
    "bloglist-client",
    () =>
        getItems<Blog>({
            collection: "blog",
        }),
    {
        server: false,
    }
);
</script>

<template>
    <div>
        <div>
            <p>Server Side</p>

            <div>
                {{ error }}
            </div>
            <p v-if="loading">Loading...</p>
            <pre v-else>{{ blogList }}</pre>
        </div>
        <div>
            <p>Client side</p>
            <p v-if="loadingClient">Loading...</p>
            <pre v-else>{{ blogListClient }}</pre>
        </div>
    </div>
</template>

```

the result
![image](https://github.com/Intevel/nuxt-directus/assets/45350572/4abce2dd-73fd-4dc0-b4a8-450d3e8e8fe4)

**Comment by Sandros94** [comment]
While to me, at first glance, this doesn't much look like a nuxt-directus issue. Could you confirm that you aren't getting hydration errors/warnings in the browser's devtool console?

**Comment by hi-reeve** [comment]
> While to me, at first glance, this doesn't much look like a nuxt-directus issue. Could you confirm that you aren't getting hydration errors/warnings in the browser's devtool console?

no there is no hydration error

![image](https://github.com/Intevel/nuxt-directus/assets/45350572/4e3de6e1-9765-43ba-9881-1e49e2709562)

**Comment by Intevel** [comment]
Is there any chance that you can create a smaller reproduction project whichs only related to nuxt-directus?

**Comment by hi-reeve** [comment]
> Is there any chance that you can create a smaller reproduction project whichs only related to nuxt-directus?

yes. here's the link 

https://github.com/hi-reeve/nuxt-directus-bug

**Comment by hi-reeve** [comment]
> > > Is there any chance that you can create a smaller reproduction project whichs only related to nuxt-directus?
> > 
> > 
> > yes. here's the link. i use sqlite on this one so you should easily setup this one
> > https://github.com/hi-reeve/nuxt-directus-bug
> 
> Other than filling up the `.env`s and adding a generic cors to directus with `CORS_ENABLED=true` and `CORS_ORIGIN=*`, everything works fine on my side
> 
> ![image](https://private-user-images.githubusercontent.com/13056429/289066357-43419662-d0a1-4c3b-b183-44a60d838f8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNjA4NDAsIm5iZiI6MTcwMjI2MDU0MCwicGF0aCI6Ii8xMzA1NjQyOS8yODkwNjYzNTctNDM0MTk2NjItZDBhMS00YzNiLWIxODMtNDRhNjBkODM4ZjhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDAyMDkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4ZDM1Yjk1NGMwYzA3N2ZmM2RiYmVkYmY4NTE3ZTY4YTg0NmY1MTIxODYwNjQwOTI1ZGZmMWJiMDIyNzE4NDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lcdH0vs3jTXHtAKfm8w1-p4qlCzfNC_vPXO5bzRm3AE)

sadly this is not working on my side.
setting up cors still have the issue for me
please reopen this @Intevel

**Comment by Intevel** [comment]
And there is no error from nuxt-directus logged in the browser console?

**Comment by hi-reeve** [comment]
> > what should i do to provide more information?
> 
> That's the hard part, basically any log/error regarding fetch or directus could help. But if you see none both in the browser console and server terminal we don't have something to debug.
> 
> Currently I have no idea in mind other than starting from a clean state (no `.nuxt` and `node_modules` folders), but I suppose you already did this when creating the second, smaller, reproduction.

![image](https://github.com/Intevel/nuxt-directus/assets/45350572/7b19a98d-6cc0-4339-abaa-cfb9621c1684)

here im just trying to directly use directus sdk and even using directus sdk directly got an error fetching the data from server side using async data. i supposed this has something to do with directus sdk or directus setup, but still cannot find the source of the problem

**Comment by Sandros94** [comment]
> here im just trying to directly use directus sdk and even using directus sdk directly got an error fetching the data from server side using async data. i supposed this has something to do with directus sdk or directus setup

Could you use [Postman](https://www.postman.com/)/[Hoppscotch](https://hoppscotch.io/)/[HTTPie](https://httpie.io/) to quickly test your `http://localhost:8055/items/posts` REST API endpoint? This way we could simply rule out a potential Directus setup/config problem and focus on Nuxt side of things

**Comment by hi-reeve** [comment]
> > here im just trying to directly use directus sdk and even using directus sdk directly got an error fetching the data from server side using async data. i supposed this has something to do with directus sdk or directus setup
> 
> Could you use [Postman](https://www.postman.com/)/[Hoppscotch](https://hoppscotch.io/)/[HTTPie](https://httpie.io/) to quickly test your `http://localhost:8055/items/posts` REST API endpoint? This way we could simply rule out a potential Directus setup/config problem and focus on Nuxt side of things

yes, it does work. so it is nuxt related problems?

**Comment by Intevel** [comment]
Can you try to make the request using ofetch and check if the issue still persists?

**Comment by hi-reeve** [comment]
> Can you try to make the request using ofetch and check if the issue still persists?

![image](https://github.com/Intevel/nuxt-directus/assets/45350572/2e07826a-5c28-4d53-8420-7ee9e250ef11)

this is the result

**Comment by hi-reeve** [comment]
i found a solution, i think this happen related to this error on nodejs 18 https://github.com/nodejs/node/issues/40702
the error occurs when i use node `18.16.0`
i tried upgrading to node `18.19.0` and it is works fine now. i don't know if this is an ideal solution

**Comment by Sandros94** [comment]
> i found a solution, [...] and it is works fine now.

You mean with `ofetch` and not only `fetch native` right?
Indeed I'm currently on node `20.6.1` so that might be it

**Comment by hi-reeve** [comment]
> > i found a solution, [...] and it is works fine now.
> 
> 
> 
> You mean with `ofetch` and not only `fetch native` right?
> 
> Indeed I'm currently on node `20.6.1` so that might be it

yes i tried everything including axios. and the result the same. the only solution is to upgrade node version

**Comment by hi-reeve** [comment]
> > i found a solution, [...] and it is works fine now.
> 
> You mean with `ofetch` and not only `fetch native` right? Indeed I'm currently on node `20.6.1` so that might be it

can you help confirm this also happen when you use node `18.16.0` ?

**Comment by Sandros94** [comment]
> can you help confirm this really happen when you use node `18.16.0` ?

I'll try to test it, once I get back home

**Comment by Sandros94** [comment]
So, I can confirm that on `18.16.0` there is indeed a fetch issue, so updating it is the way to go.
![image](https://github.com/Intevel/nuxt-directus/assets/13056429/c62f2db0-127e-4264-925b-355f4b072b6d)

But now that I think about it I remember reading in the [nuxt `3.8.0` release](https://github.com/nuxt/nuxt/releases/tag/v3.8.0) a fetch rewrite using native note fetch for [nitro `2.7.0`](https://github.com/unjs/nitro/releases/tag/v2.7.0), more in particular in [nitro/#724](https://github.com/unjs/nitro/pull/1724).

Anyway, I would consider this issue closed since, to me, it does not seem to be directly related to nuxt-directus itself, but just a combination of node+nuxt versions

**Comment by hi-reeve** [comment]
> So, I can confirm that on `18.16.0` there is indeed a fetch issue, so updating it is the way to go.
> 
> ![image](https://github.com/Intevel/nuxt-directus/assets/13056429/c62f2db0-127e-4264-925b-355f4b072b6d)
> 
> 
> 
> But now that I think about it I remember reading in the [nuxt `3.8.0` release](https://github.com/nuxt/nuxt/releases/tag/v3.8.0) a fetch rewrite using native note fetch for [nitro `2.7.0`](https://github.com/unjs/nitro/releases/tag/v2.7.0), more in particular in [nitro/#724](https://github.com/unjs/nitro/pull/1724).
> 
> 
> 
> Anyway, I would consider this issue closed since, to me, it does not seem to be directly related to nuxt-directus itself, but just a combination of node+nuxt versions

thankyou!
