### ISSUE TITLE
useDirectusFiles 500 useDirectus is not defined

### ISSUE THREAD

**Issue by loongmxbt** [Intevel/nuxt-directus#23]
### Version

nuxt-directus 1.7.1
nuxt: 3.0.0-rc.1

### Steps to reproduce
When add `const { getThumbnail } = useDirectusFiles();` to <script setup> 
```
<script setup>
const { getItems } = useDirectusItems();
const { getThumbnail } = useDirectusFiles();

const posts = await getItems({ collection: "web_post" });
</script>
```
Shows the error
<img width="1314" alt="image" src="https://user-images.githubusercontent.com/5986600/164965080-b5a1ef83-2d12-4bb7-b796-bda97b27235b.png">

### What is Expected?
I tried other useXXX doesn't cause the error. Don't know how to correctly use `useDirectusFiles`.

**Comment by Intevel** [comment]
Hey, thank you for opening an Issue. Can you maybe provide a repository link or an other way for reproduction?

**Comment by Intevel** [comment]
Hey, thanks. It's an import issue. I will fix it!

**Comment by Intevel** [comment]
Update to version `1.8.0` should fix this @loongmxbt
