### ISSUE TITLE
support to upload files through via this module

### ISSUE THREAD

**Issue by yaroslav-mygal** [Intevel/nuxt-directus#237]
wrapper for Directus SDK directus.files.createOne

Have you any function for this SDK function?

Thanks.

**Comment by Sandros94** [comment]
If you are referring to the `nuxt-directus-next` module then it is based on the _NEW_ SDK, so syntax is a bit different, and yes we do have a function to directly upload files via:

```js
const { uploadFiles } = useDirectusFiles()

const formData = new FormData()
formData.append('file_1_property', 'Value')
formData.append('file', raw_file)
formData.append('file_2_property', 'Value')
formData.append('file', raw_file_2)

const result = await uploadFiles(formData)
```

or via link:

```js
const { importFile } = useDirectusFiles()

const result = await importFile(file_url, file_object)
```

Be aware that `nuxt-directus-next` is still being finalized and not yet fully stable, so if you do find any issue while implementing the code above feel free to reopen this issue by providing a reproduction link to a git repo or stackblitz.
