### ISSUE TITLE
Unable to consume Directus API

### ISSUE THREAD

**Issue by timothybennette8** [Intevel/nuxt-directus#240]
I have been trying in vain to get nuxt-directus to connect to my directus instance and I can't get them to communicate.
I have Nuxt and Directus running in the same Docker container through a reverse-proxy, Nuxt is mapped to "localhost/" and Directus to "localhost/directus". Both run and behave as expected in isolation.

I have set my nuxt.config like so:
```
  modules: ["nuxt-directus"],
  runtimeConfig: {
    directus: {
      url: "http://localhost/directus",
    },
  }
```

In a Nuxt page I try this:
```
  const { login } = useDirectusAuth();
  const user = useDirectusUser();

  await login({ email: "<admin email>", password: "<admin password>" });

  console.log("User", user.value)
  ```
And it returns this:
![directus](https://github.com/Intevel/nuxt-directus/assets/43624464/c316bf01-c51e-47af-898d-3397ed18084f)

I don't know what to do at this point, as I've done what the documentation says and I've run out of forum posts to try.

I have successfully adapted https://github.com/srjrol/directuxt to use my database and in the main it works, although not hot-reloading, and I'd rather not use a load of TS that I don't understand as the foundation to my project/s!

**Comment by casualmatt** [comment]
Hello, 
Can you send the docker file or the repo link?
Btw docker guidelines are not to mix multiple processes, so I suggest using a docker-compose, with Directus, postgres, redis, and Nuxt as stand-alone containers, all exposed on the docker network.

**Comment by timothybennette8** [comment]
I do use docker-compose, and I *think* in the manner you mean (I'm pretty new to Docker).
[Here's my project as it stands: ](https://github.com/timothybennette8/nuxt-directus-docker) - (note the example.env files in the root and /nuxt).
For my database I use a cloud instance of Supabase which works fine from the Directus backend.

**Comment by casualmatt** [comment]
Oh okay, then use the docker container host or their IP in the docker local network. 
Localhost is the localhost inside that container.

**Comment by timothybennette8** [comment]
That's what I thought I was doing :(
