### ISSUE TITLE
type issues during build

### ISSUE THREAD

**Issue by Sandros94** [Intevel/nuxt-directus#242]
While deploying `nuxt-directus-next@0.0.10` I've noticed that a strange error pops while trying to build the module with `@directus/sdk@15.0.x`.

This is easily reproducible by checking out the `dev` branch before reverting back to `14.0.0` [here](https://github.com/Intevel/nuxt-directus/tree/3038a682f2cf47bb495c7f702cfdc7252f1d5d04), then doing:
```bash
pnpm install && pnpm dev:prepare && pnpm prepack
```

The following error comes up

```bash
> nuxt-directus-next@0.0.9 prepack A:\github\Intevel\nuxt-directus
> nuxt-module-build build

ℹ Building nuxt-directus-next                                                                                                                                                            20:10:20
ℹ Cleaning dist directory: ./dist                                                                                                                                                        20:10:20   
src/runtime/composables/use-directus-files.ts(21,17): error TS7056: The inferred type of this node exceeds the maximum length the compiler will serialize. An explicit type annotation is needed.
src/runtime/composables/use-directus-notifications.ts(21,17): error TS7056: The inferred type of this node exceeds the maximum length the compiler will serialize. An explicit type annotation is needed.
src/runtime/composables/use-directus-revisions.ts(15,17): error TS7056: The inferred type of this node exceeds the maximum length the compiler will serialize. An explicit type annotation is needed.
src/runtime/composables/use-directus-users.ts(33,17): error TS7056: The inferred type of this node exceeds the maximum length the compiler will serialize. An explicit type annotation is needed.   


 ERROR  Failed to compile. Check the logs above.                                                                                                                                          20:10:25  

  at error (/A:/github/Intevel/nuxt-directus/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
  at Object.error (/A:/github/Intevel/nuxt-directus/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:25351:20)
  at Object.error (/A:/github/Intevel/nuxt-directus/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:24472:42)
  at generateDtsFromTs (/A:/github/Intevel/nuxt-directus/node_modules/.pnpm/rollup-plugin-dts@6.1.0_rollup@3.29.4_typescript@5.3.3/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.mjs:1833:30)
  at Object.transform (/A:/github/Intevel/nuxt-directus/node_modules/.pnpm/rollup-plugin-dts@6.1.0_rollup@3.29.4_typescript@5.3.3/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.mjs:1842:38)
  at /A:/github/Intevel/nuxt-directus/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:25544:40
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)


 ERROR  Failed to compile. Check the logs above.                                                                                                                                          20:10:25  

 ELIFECYCLE  Command failed with exit code 1.
```

While checking out those files the only thing that I could find in common was that they had a number of types like [this one](https://github.com/Intevel/nuxt-directus/blob/776ab2cddce368d0792c330c10e8e8c72a20ad54/src/runtime/composables/use-directus-revisions.ts#L32):
```ts
id: DirectusRevision<TSchema>['id']
```

And if I try in fact to change `TSchema` with a generic `any` (to those affected functions as well their related clients), the error goes away and builds successfully.

**Comment by happy-turtle** [comment]
Maybe you have found this already, but there is a type import change from sdk `v14` to `v15`: https://github.com/directus/directus/commit/a7e32f386e15d247c5de731aceab5d4ea4ed019e. Maybe the directus sdk imports need to be updated? And yes, this is somewhat related to #244 . 😄

**Comment by Sandros94** [comment]
Note to myself: double check if [this helps](https://nuxt.com/blog/v3-11#type-fixes).

**Comment by Sandros94** [comment]
released with `nuxt-directus-next@0.0.13`

**Comment by Sandros94** [comment]
With #250 it is clear that this issue isn't fully solved yet, but now the main limitation comes from nuxt during build

**Comment by Sandros94** [comment]
> With #250 it is clear that this issue isn't fully solved yet, but now the main limitation comes from nuxt during build

I'm closing this for now, since not only `nuxt-directus-next@0.0.14` does solve the last few issues related to #250, but also I'm starting to think of an environment issue that I'm using to build the module (Win11Pro `23H2-22631.3296`, `nvm@1.1.11`, `node@20.11.1`).

Currently I don't have much time to debug it further.
