### ISSUE TITLE
cant retrieve folders from directus

### ISSUE THREAD

**Issue by PhilipZi** [Intevel/nuxt-directus#246]
the library wont let me retrieve my folders from directus. 

see my code: 

```
const { getItems } = useDirectusItems();

export const useBlockStore = defineStore("blocks", {
  state: () => ({
    blockContent: [],
  }),

  actions: {
    async updateContent() {
      try {
        this.blockContent = await getItems({
          collection: "support_portal",
          params: { fields: ["*.*.*.*"] },
        });
      } catch (e) {}
    },
  },
});

```

This is my code to reach a collection called support portal. This works. But i cant reach folders inside this collection nor can i reach folders created by me and directly speaking to them, i need somethins else than " collection" i guess. somethins like "folders" which i can filter threw. Do you have some ideas? Is there a solution?

This is my data structure. I would like to reach block_hero_banner and some other blocks which are coming next to block_hero_banner. see my image:

<img width="928" alt="Bildschirmfoto 2024-02-15 um 17 16 47" src="https://github.com/Intevel/nuxt-directus/assets/102238180/1bd01c65-dfdb-47b5-99d4-d6a1334b1e24">

Hope you can help me.

**Comment by casualmatt** [comment]
Hi @PhilipZi, 
can you send a link of a repo or stackblitz? 
What version of the module are you using 5.x or 6.x? 

Btw, a query like this: "*.*.*.*" will use a lot of resources, I would highly discourage wildcard usage, even if you use Directus+Postgress, and especially if you use other DB.

**Comment by PhilipZi** [comment]
Hey Matt, thanks for the quick reply! 
Its on gitlab and i cant really share the repo unfortunately. 
![Bildschirmfoto 2024-02-15 um 18 15 31](https://github.com/Intevel/nuxt-directus/assets/102238180/dae5c223-6d6d-4e9c-825a-2681cf5f2108)

i am using 1.3 anyhow? If you mean the nuxt-directus lib? 
I can provide you more code snippets if this helps? What you saw earlier is a snippet from a pinia store. It works as it is shown the only thing i need is to reach the folder and the collections inside that folder which is nested in one collection. 
It would also help if i can just reach collections inside of folders.

**Comment by PhilipZi** [comment]
![Bildschirmfoto 2024-02-15 um 18 19 58](https://github.com/Intevel/nuxt-directus/assets/102238180/96013390-7281-4c50-af8e-4125ab276d32)

actually i am using 5.6 xD i screen shot the wrong dep.

**Comment by PhilipZi** [comment]
I also set the public accessibility for directus_folders and directus_collections to visibile/readable

**Comment by Sandros94** [comment]
If I understand correctly the `folders` endpoint they are meant for files and not collections. [Official docs](https://docs.directus.io/reference/system/folders.html):

> Folders can be used to organize files within the platform. Folders are virtual, and aren't mirrored within the storage adapter.

But in your screenshot above:

> <img alt="Bildschirmfoto 2024-02-15 um 17 16 47" width="928" src="https://private-user-images.githubusercontent.com/102238180/305143577-1bd01c65-dfdb-47b5-99d4-d6a1334b1e24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMTkwNzgsIm5iZiI6MTcwODAxODc3OCwicGF0aCI6Ii8xMDIyMzgxODAvMzA1MTQzNTc3LTFiZDAxYzY1LWRmZGItNDdiNS05OWQ0LWQ2YTEzMzRiMWUyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNVQxNzM5MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZWI4YWMyMGJjZGU0NDQzNjk0ZDA1OTMwN2YyYTkwYWVhZmYyMjVjMjBkMjRkMWVjYTViOTk2ZGE3NmIwMDI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.L87nLxsY8Np6rWEtXb39PaDwP8nuB9jus1NgV1gY2ME">

It seems like you are referring to `folders` for collections and not files right? If this is the case I'm not sure if they can be used in the API/SDK or they are just a visual representation of the Directus app

**Comment by PhilipZi** [comment]
thanks Sandros, this is actually correct, but when i speak to the support_portal collection for example i wont be able to reach block_hero_banner, its not shown in the api even if i put away the folder. 
You got me right there. This is my main issue. later on i wanna have multiple collections inside support_portal which i would like to generate with one request if possible.

**Comment by PhilipZi** [comment]
To make it more clear is there a build in function to reach the folders content? It seams via @directus/sdk lib i could reach these? See my sceenshot. 

![Bildschirmfoto 2024-02-16 um 08 55 22](https://github.com/Intevel/nuxt-directus/assets/102238180/3dd26b39-21e2-49b6-a138-f9989dc84659)

here it seems to be possible to reach the folders. but in nuxt-directus this option is not documented or working. 
I need to use nuxt-directus lib because with the other lib nuxt-images wont get rendered in webp format... 

would be happy if someone can help out.

**Comment by casualmatt** [comment]
Yes, but that is the virtual folder that Directus uses; it's just a table in the DB called `directus_folders.` 
In any case, you can't use read folders for a folder table that you created; it works only with Directu's own folder system. 

If you want to use the SDK, you could try the 6.x version of the module that is in development and directly works with the SDK, but version 5.x is based on Directus API non SDK:

**Comment by Sandros94** [comment]
Also, as @casualmatt mentioned, the 6.x currently available in pre-release under `nuxt-directus-next` already has support for `@nuxt/image`.

Again, the folders you are mentioning (in `/admin/settings/data-model` if your Directus App), as far as I remember, aren't the folders under the `readFolders` composable from the SDK. Did you double check your permissions for the `block_hero_banner` collection, and have a valid relation from `support_portal` and a junction collection (that is missing from the information provided so far)?

Please refer to the [official docs](https://docs.directus.io/guides/headless-cms/reusable-components.html) on how to build reusable page components. If you are going to use [`nuxt-directud-next`](https://next.nuxt-directus.site) you can also use clients (our docs about the SDK are still being drafted).

**Comment by casualmatt** [comment]
@PhilipZi We are not able to reproduce your issue/request. 
For now, I will close the issue as "Not planned/stale". If, in the future, you are able to provide a Stackblitz link, we will go over it again and try to help you.

**Comment by PhilipZi** [comment]
Thanks a lot guys i understand now. I found a way around. 
Much appreciate you help.
