### ISSUE TITLE
Promise<any> in readItemsAsync in next versions

### ISSUE THREAD

**Issue by Nisgrak** [Intevel/nuxt-directus#250]
### Version

nuxt-directus-next: v0.0.13

### Reproduction Link

https://www.npmjs.com/package/nuxt-directus-next?activeTab=code
![image](https://github.com/Intevel/nuxt-directus/assets/19597708/c21258e9-768b-4290-a88e-7448ddddde19)
![image](https://github.com/Intevel/nuxt-directus/assets/19597708/15e6644e-c519-47e8-8c6a-bf6a00255fb1)

### What is Expected?
The readAsync functions has the correct Generic Type in combination with SDK response
### What is actually happening?
Looks like it generate Promise<any>
In the code it returns an actual any

**Comment by Sandros94** [comment]
While working on this I found a few other things in regard to the current `useAsyncData` implementation.

Once closed I'll push `0.0.14`

**Comment by Sandros94** [comment]
pushed `0.0.14`, feel free to reopen if you see more, related, problems
