### ISSUE TITLE
add params (global query parameters) for update and create item(s)

### ISSUE THREAD

**Issue by docloulou** [Intevel/nuxt-directus#257]
Hello,

### Is your feature request related to a problem? Please describe.
I noticed that the update item API REST supports global query parameters. For my project, I need to access relational fields from the PATCH/POST return.
 
### Describe the solution you'd like
include the fields params for createItems & updateItem 

`    const items = await createItems<Article>({
      collection: "News",
      items,
      params: {
        fields: ['*.*'],
      },
    });
`

code to edit : https://github.com/Intevel/nuxt-directus/blob/5a79a7c50021cedd901240c356e3581198266cca/src/runtime/composables/useDirectusItems.ts#L82

https://github.com/Intevel/nuxt-directus/blob/5a79a7c50021cedd901240c356e3581198266cca/src/runtime/composables/useDirectusItems.ts#L67

### Describe alternatives you've considered
Today, I'm obliged to refetch by ID after a PATCH/POST operation.

Many thanks

**Comment by casualmatt** [comment]
Merge request #258 solve this issue.
