### ISSUE TITLE
Formkit + nuxt-directus-next not working

### ISSUE THREAD

**Issue by ChuckMoe** [Intevel/nuxt-directus#260]
Hey everyone!
This is gonna be tricky and very specialized I know, but I am uncertain where exactly I should post this.

In order to make an update form, I am currently trying to read some data from my Directus backend and pass it into the Formkit form.
The Formkit form itself works perfect. I am already using it to create items in the backend.
nuxt-directus-next works also perfectly fine, as I get all the data I need in another place.
As soon as I put both together in one file, I get the following though:

```
500
[nuxt] A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug. Find out more at `https://nuxt.com/docs/guide/concepts/auto-imports#vue-and-nuxt-composables`.

at Module.useRuntimeConfig (./node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.59.4_encoding@0.1.13_fl_ljclzznsqjibupl7wngmkvqggi/node_modules/nuxt/dist/app/nuxt.js:226:27)
at ./formkit.config.ts:16:40
at ./node_modules/.pnpm/@formkit+vue@1.6.2_tailwindcss@3.4.3_unocss@0.59.4_@unocss+webpack@0.59.4_rollup@4.17.0_webpa_iv43egqiei23zsjkqkyobxgs7i/node_modules/@formkit/vue/dist/index.dev.mjs:1353:47
at FormKitConfigLoader2 (./node_modules/.pnpm/@formkit+vue@1.6.2_tailwindcss@3.4.3_unocss@0.59.4_@unocss+webpack@0.59.4_rollup@4.17.0_webpa_iv43egqiei23zsjkqkyobxgs7i/node_modules/@formkit/vue/dist/index.dev.mjs:2012:16)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I guess this is me being new to Vue/Nuxt and not quite understanding what I am doing wrong.

---

nuxt-directus-next: 0.0.15
nuxt: v3.11.2
formkit: v1.6.2

**Comment by Sandros94** [comment]
> This is gonna be tricky and very specialized I know, but I am uncertain where exactly I should post this.

Surely we can start here, but I would require a reproduction with: 
- the current config (in particular `directus` inside `nuxt.config.ts`)
- the composable/component/page you are using them together that triggers the error

**Comment by ChuckMoe** [comment]
I have no idea why this was a problem, but changing from a functional way of defininf my formkit config to simply exporting the definition worked like a charm. See the discussion [here](https://discord.com/channels/793529058377072650/1235251822642593812).

Thanks anyway @Sandros94 !
