### ISSUE TITLE
Cannot get user (me)

### ISSUE THREAD

**Issue by BorisKamp** [Intevel/nuxt-directus#269]
### Version

nuxt-directus `^5.6.1`
nuxt: `^3.12.4`

Hi!

I can successfully login using this code:
```javascript
async function submitForm() {
  const isFormCorrect = await v$.value.$validate()

  if (isFormCorrect) {
    loading.value = true

    login(loginData.value)
      .then((response) => {
        if (response) {
          emit('onLogin')
          useNotificationsStore().addNotification(successNotification)
        }
      })
      .catch((e) => {
        console.error(e)
      })
      .finally(() => {
        loading.value = false
      })
  }
}
```

I see the tokens set 
<img width="406" alt="Screenshot 2024-08-08 at 11 24 53" src="https://github.com/user-attachments/assets/8fa7c617-66a5-4df5-af9e-99cd97acfa9f">

When I use these tokens in postman, I get can the user. When  I refresh in Nuxt, I **always get a 401**. When I inspect the request, I see no Authorization header sent, how is this possible? This is taking me hours already.

<img width="1347" alt="Screenshot 2024-08-08 at 11 25 58" src="https://github.com/user-attachments/assets/9ede8fc3-dd10-44cd-b0fc-ca7be4e814a1">

**Comment by Sandros94** [comment]
Could I ask you further clarification on "When I refresh in Nuxt"? Refrehing the page that makes the request or refreshing the token?

**Comment by casualmatt** [comment]
Closed for inactivity
