### ISSUE TITLE
Docs are down

### ISSUE THREAD

**Issue by adamkhan** [Intevel/nuxt-directus#270]
Looks like the nuxt-directus.site domain needs renewing or the docs moved somewhere else. Is help needed here, ie, paying for domain?

### Version

nuxt-directus 
nuxt:

**Comment by Sandros94** [comment]
Thanks @adamkhan, we'll move it shortly to a new domain

**Comment by grafitborz** [comment]
And when exactly will that be? Need the docs to work!

**Comment by kheiner** [comment]
Two temporary solutions for ya!

### 1. Visit an archived version of the docs:
available at [archive.org](https://web.archive.org/web/20240227233804/https://www.nuxt-directus.site/composables/usedirectusitems)

### 2. Create a local copy:

run the following commands in your terminal

`git clone http://github.com/intevel/nuxt-directus`
`cd nuxt-directus/docs`
`npm i`
`npm run dev`

**Comment by grafitborz** [comment]
thanks a lot!

**Comment by Intevel** [comment]
Moved to a new domain: https://nuxt-directus.de/

👍🏼

**Comment by Krislunde** [comment]
> Moved to a new domain: https://nuxt-directus.de/
> 
> 👍🏼

Maybe update the nuxt module page to point to the new location instead of the old .site domain.

**Comment by sandros94** [comment]
> Maybe update the nuxt module page to point to the new location instead of the old .site domain.

Which module page are you referring to? The one at `nuxt.com/modules/directus'?
If that is so, there could be a local-cache issue. That link has already been updated to the correct one

**Comment by Krislunde** [comment]
> That link has already been updated to the correct one

The link to the documentation in the `links` sidebar has been correctly updated, but not the link url for the `Read the documentation` link in the main content area.

**Comment by Stretsh** [comment]
This page needs to be updated too: https://docs.directus.io/blog/nuxt-directus-getting-started.html
