### ISSUE TITLE
401 unauthorized when running the playground

### ISSUE THREAD

**Issue by Nisthar** [Intevel/nuxt-directus#275]
### Version

nuxt-directus 5.6.1
nuxt: Nuxt 3.2.

### Steps to reproduce
1. cloned the git repo
2. run pnpm install and pnpm dev:prepare
3. run pnpm dev

### What is actually happening?
After successful login, refresh the page and you get 401 unauthorized 
![image](https://github.com/user-attachments/assets/f7847d34-e909-49f2-a951-f27914e8719e)

Is it something wrong with my directus instance or the library?

**Comment by sandros94** [comment]
Ehy @Nisthar, since the new rewrite will take a bit before becoming usable, I started taking a look at this, but I'm not able to reproduce this issue.

Could I ask you to setup a small reproduction using the https://directus.pizza instance? (the test user is admin@example.com + password)

**Comment by sandros94** [comment]
Also, just noticed that in this screenshot I see "Invalid user credentials" in the 3rd line

**Comment by Nisthar** [comment]
@sandros94 Yeah i found out the issue causing it. It was because of the ssl, i had to set NODE_TLS_REJECT_UNAUTHORIZED=0 in the env since i was using ssl in development.
