### ISSUE TITLE
how to correctly access nested fields

### ISSUE THREAD

**Issue by MartinConde** [Intevel/nuxt-directus#277]
I feel like I'm missing something obvious but after not being able to figure it for a while, I figured I'd ask here. 
I have some nested blocks, which when using the "regular" sdk, I can get like so:
```
...
fields: [
  "*",
  {
    blocks: [
      "collection",
      {
        item: {
          block_hero: ["*"],
          block_intro: ["*"],
          block_cards: ["*"],
          block_image: ["*"],
          block_gallery: ["*.*"],
        },
      },
    ],
  },
];
```
However when I try to do the same thing using this module and following the useAsyncData example in the docs, it doesn't return any of the blocks, only the first set of "first-level" fields that it grabs using '*'.`
Doing something like

`fields: ['*.*.*.*']`

does return everything but I'd just like to figure out how to properly return the selected data.

Any pointers on what I might be missing to get this working would be much appreciated!

**Comment by MartinConde** [comment]
Thanks a lot! Just in case anybody else stumbles upon this, the simplest way to get a list of all the blocks with the respective collection name for conditional rendering and whatnot, was simply:
```
fields: [
      'blocks.collection',
      'blocks.item.*',
]
```

**Comment by sandros94** [comment]
I'm going to close this for now, since I would like to focus on an initial release of the rewrite and revisit this in a later date.

Please do comment or re-open it if something might come to mind!
