### ISSUE TITLE
[Directus Error]: FetchError: [GET] "http://localhost:8055/items/item_name": <no response> fetch failed

### ISSUE THREAD

**Issue by chrisnaadhi** [Intevel/nuxt-directus#279]
### Version

nuxt-directus v5.6.1
nuxt: v3.13.2
directus: v11.1.2

### Reproduction Link

https://github.com/chrisnaadhi/directus-exp

### Steps to reproduce

Fresh installation of Nuxt and Directus and add nuxt-directus module

### What is Expected?
Can read items and display it to vue template or console log it

### What is actually happening?
Got Directus Error, can't fetch undefined (_data)
![image](https://github.com/user-attachments/assets/a9ab2eac-e08c-4ad0-8cb0-94202cabaafd)

![image](https://github.com/user-attachments/assets/d016d4bb-b5b7-449a-bf67-1662db49b34d)

**Comment by Intevel** [comment]
Can you try to reproduce this with an other HTTP Client? And send such a request.

**Comment by chrisnaadhi** [comment]
> Can you try to reproduce this with an other HTTP Client? And send such a request.

i'm already use plain request via web and postman / similar rest client, it was working perfect i got the result
but when using the library i got the directus error (actually i've tried the @directus/sdk, but bit complicated and the tutorial from official website was not working)

**Comment by chrisnaadhi** [comment]
seems like it was my office network problem
solved with of the IP configuration on my office network
