### ISSUE TITLE
Uploading User Avatars to Directus

### ISSUE THREAD

**Issue by yavuz** [Intevel/nuxt-directus#280]
Hi,

I am currently developing a Nuxt project where I want users to be able to upload their avatars. How can I integrate this feature? What steps should I follow for user avatar upload in Directus?

Thanks!

**Comment by yavuz** [comment]
I have created a pull request for this. https://github.com/Intevel/nuxt-directus/pull/281

**Comment by sandros94** [comment]
Sorry @yavuz if this hasn't received any attention 🙏

The main reason is that I'm currently blocked by other projects and the work on #273, while @Intevel is currently unavailable.

Thank you so much for the PR, although I cannot currently help on `v5`

**Comment by Intevel** [comment]
Thanks for your PR @yavuz. Released with v5.7.0
