### ISSUE TITLE
Add GraphQL Support

### ISSUE THREAD

**Issue by Intevel** [Intevel/nuxt-directus#3]

**Comment by productdevbook** [comment]
Why was this topic closed ?

**Comment by vanling** [comment]
> Why was this topic closed ? 

I guess because it has been added to the in v1.8.0.

**Comment by productdevbook** [comment]
https://github.com/Intevel/nuxt-directus/commit/358bbf6d4c418741c5528b3d083f054d6efbb355

Yes, I saw the code now, but I think it might be a better structure, I will work on it.

**Comment by productdevbook** [comment]
```Vue Apollo``` -> https://v4.apollo.vuejs.org/

I'm thinking of integrating that into this build. I did it in Vuede, but I don't know how to do it on nuxt side, I have to research it. Maybe it will help when I create a pr.

But I don't know if it is right to integrate this structure here.

**Comment by Intevel** [comment]
Any updates on this? @productdevbook

**Comment by productdevbook** [comment]
Since I have little free time per week, I am in research.  When I find a logical solution, I will give information here.  I am working on monorepo in a similar project.  I haven't been able to find a fully keain bie solution yet.

**Comment by narduin** [comment]
> [358bbf6](https://github.com/Intevel/nuxt-directus/commit/358bbf6d4c418741c5528b3d083f054d6efbb355)
> 
> Yes, I saw the code now, but I think it might be a better structure, I will work on it.

Hi!
Is it currently possible to use graphql requests with this module? I'm not quite sure of how to proceed, sorry…

**Comment by Intevel** [comment]
Currently not.
