### ISSUE TITLE
Use access_token authentication method

### ISSUE THREAD

**Issue by craigharman** [Intevel/nuxt-directus#31]
### Is your feature request related to a problem? Please describe.
You currently can't use the Directus access token method to authenticate to the API.
Ie. I share the "token" from the User > Admin Settings section and provide that in the Query String or the Authorization Bearer header.

### Describe the solution you'd like
login should accept a {"token" OR { email:  string, password: string }

```ts
<script setup lang="ts">
const { login } = useDirectusAuth();
const router = useRouter();

const onSubmit = async () => {
  try {
    await login({ token: "" });
  } catch (e) {}
};
</script>
```

**Comment by craigharman** [comment]
Just saw https://github.com/Intevel/nuxt-directus/pull/16 so closing.

**Comment by vanling** [comment]
I don't think #16 is fixing the problem you describe right? 
Related https://github.com/Intevel/nuxt-directus/discussions/27

**Comment by Intevel** [comment]
@vanling You are right, this does not solve the problem. I will reopen this issue.

**Comment by craigharman** [comment]
I have done some more research and you are correct, this request is to use the stand-alone user token not JWT. You can append a query string ?access_token to each request but a way to add the Authorization Bearer header would be better IMO.

**Comment by rvmourik** [comment]
This indeed would be a nice feature to have an option to send the token through headers instead of the querystring.

**Comment by Intevel** [comment]
https://docs.directus.io/reference/authentication/#login

According to the Directus documentation, the login endpoint does not accept a token.

**Comment by vanling** [comment]
@Intevel It's not so much for user authentication but for api access via an static token you can set per user.
https://docs.directus.io/reference/authentication/#access-tokens

Would love to be able to add a token in the nuxt config
```
  directus: {
    url: "https://url-to-directus-api.ext/",
    token: "5cc14101-11d3-4420-8067-a28750b4635f"
  },
  ```
And the idea is that the token would be used in an Authorization Bearer header for every request.

For example, i create a user in Directus called "api_application" and give that user a static access token.
![image](https://user-images.githubusercontent.com/50699657/168340678-03447863-669c-454b-8e45-b7803740cc12.png)
I also create a Role for this user and this way I can use the api without making everything public.

Now i can make specific data available to the public for a single application

**Comment by Intevel** [comment]
@vanling I would say that we add to the `DirectusQueryParams` type the `access_token` and then you specify it via the method params. 

At the setup of the module the options are merged with the public runtime config, the token would be revealed.

**Comment by Intevel** [comment]
Related to #27

**Comment by vanling** [comment]
It would be ok to reveal the token to public if that's the choice of the user. Would just need to be clear in the documentation that this would be the case.

I create tokens with restricted read/write access for different websites that use the same directus api/instance. This way I can block an application by removing a key and also see which application has written data into the api.

_Directus SDK example: https://docs.directus.io/reference/sdk/#with-static-tokens_
