### ISSUE TITLE
Require NUXT_DIRECTUS_URL in .env

### ISSUE THREAD

**Issue by craigharman** [Intevel/nuxt-directus#33]
### Version

nuxt-directus v2.0.0
nuxt: 3.0.0-rc1

### Steps to reproduce

Add a runtime config to nuxt.config.ts. This then requires that the directus config object is moved from the root to the runtime config to access the config.directus.url object.

```ts
runtimeConfig: {
		public: {
			directusEmail: "",
			directusPassword: "",
		},
		directus: {
			url: "",
		},
	},
```

However if you do this following the set up procedure the config object then looks like this:

```js
{
  app: { baseURL: '/', buildAssetsDir: '/_nuxt/', cdnURL: '' },
  nitro: { routes: {}, envPrefix: 'NUXT_' },
  public: { directusEmail: 'admin@test.com', directusPassword: 'password' },
  directus: { url: '' }
}
```
Note the empty directus URL despite having DIRECTUS_URL in .env file.
Adding NUXT_DIRECTUS_URL to the .env file fixes this issue.

Also note that if you remove DIRECTUS_URL nuxt-directive gives an error:

`Cannot start nuxt:  Missing DIRECTUS_URL in .env`

So you now have 2x .env variables for the same thing.

### What is Expected?

Should not require NUXT_DIRECTUS_URL and it should be available in the runtime config.

### What is actually happening?

Require NUXT_DIRECTUS_URL in .env otherwise nuxt-directus cannot contact the Directus server.

**Comment by Intevel** [comment]
Is this bug still present? @craigharman

**Comment by craigharman** [comment]
Have tried this again tonight @Intevel and can confirm it is an issue **if** you use the [standard Nuxt format](https://v3.nuxtjs.org/guide/features/runtime-config/).

```javascript
runtimeConfig: {
		public: {
			directusEmail: "",
			directusPassword: "",
		},
		directus: {
			url: "",
		},
	},
```

However if you put the directus config in the root of the config and have a `publicRuntimeConfig` then it works fine:

```javascript
directus: {

},
publicRuntimeConfig: {
directusEmail: "",
directusPassword: "",
},
```

**Comment by Intevel** [comment]
What do you think we should do on this issue? @craigharman
