### ISSUE TITLE
information from "meta"

### ISSUE THREAD

**Issue by albericobenhur** [Intevel/nuxt-directus#62]
hi, I'm trying to access the "meta" information through "getItems", I had a look at the documentation but I couldn't find anything related

**Comment by albericobenhur** [comment]
I want to get the result "meta" instead of "data"

**Comment by Intevel** [comment]
Hey @albericobenhur, in the newest release you can access meta. 
`getItems` will now return data and meta

![image](https://user-images.githubusercontent.com/59223342/187069655-8f370250-841b-41bb-a691-686e7bb1e064.png)
