### ISSUE TITLE
Incompatibility

### ISSUE THREAD

**Issue by paulvonber** [Intevel/nuxt-directus#65]
### Version

nuxt-directus 3.0.0
nuxt: 3.0.0-rc.9

### Steps to reproduce
Try to use nuxt-directus with latest nuxt 3.0.0-rc.9, package is not being loaded due to incompatibility, here is mentioned that package creators should take care of this problem https://github.com/nuxt/framework/releases/tag/v3.0.0-rc.9

### What is actually happening?
<img width="778" alt="image" src="https://user-images.githubusercontent.com/37245111/188288376-6e59162b-0293-4dd3-86d9-80883514d517.png">

**Comment by Intevel** [comment]
Should be fixed with the newest version!
