### ISSUE TITLE
Aggregation & Grouping

### ISSUE THREAD

**Issue by lyneal** [Intevel/nuxt-directus#72]
Hello,

Would it be possible to offer native support for "Aggregation & Grouping" ?

**Comment by Intevel** [comment]
Hey @lyneal, sorry for the late answer. But what do you mean by Aggregation & Grouping?

**Comment by lyneal** [comment]
> Hey @lyneal, sorry for the late answer. But what do you mean by Aggregation & Grouping?

Don't worry about the late reply :) 

This is what I was referring to:
https://docs.directus.io/reference/query.html#aggregation-grouping

Personally, I didn't need it in the end, but it's an open question if you think this feature is interesting.

**Comment by Intevel** [comment]
@lyneal We should keep this issue open, this is a great feature to implement.

**Comment by rashidpathiyil** [comment]
So we can't use Aggregation & Grouping now on next?

**Comment by rashidpathiyil** [comment]
Aggregate is working for me

```js
  await getItems({
    collection: 'transactions',
    params: {
      'fields': ['*.*'],
      'filter': {
        status: 'successful',
      },
      'aggregate[sum]': 'amount',
    },
  }),
```

**Comment by notflip** [comment]
> Aggregate is working for me
> 
> ```js
>   await getItems({
>     collection: 'transactions',
>     params: {
>       'fields': ['*.*'],
>       'filter': {
>         status: 'successful',
>       },
>       'aggregate[sum]': 'amount',
>     },
>   }),
> ```

This isn't added to the DirectusQueryParams type, that's why autocomplete didn't show it

```
export interface DirectusQueryParams {
  fields?: Array<string>;
  sort?: string | Array<string>;
  filter?: Record<string, unknown>;
  limit?: number;
  offset?: number;
  page?: number;
  alias?: string | Array<string>;
  deep?: Record<string, unknown>;
  search?: string;
}
```
