### ISSUE TITLE
Add an update user method

### ISSUE THREAD

**Issue by TitusKirch** [Intevel/nuxt-directus#74]
### Is your feature request related to a problem? Please describe.
Besides the createUser({ ... }) method, I think there should be an updateUser({ ... }) method that updates the current user.

### Describe the solution you'd like
N/A

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by Intevel** [comment]
Hey, you can update the user with the `setUser` method of the `useDirectusAuth()` composable

**Comment by TitusKirch** [comment]
But setUser  set only the users and does not update the user in directus or did i understand you wrong?

**Comment by Intevel** [comment]
Ah no, sorry you are right. I understand you wrong. I reopen this issue.

**Comment by Sandros94** [comment]
I'm going to close this one. Since the new `v6`, [more info here](https://github.com/Intevel/nuxt-directus/discussions/215), does offer a number of way to update user's data:

```js
const { updateMe, updateUser, updateUsers } = useDirectusUsers()
```

Feel free to reopen or comment if you find any issue.
