### ISSUE TITLE
How to recognize an authentication error to server error 

### ISSUE THREAD

**Issue by theo-stocchetti** [Intevel/nuxt-directus#75]
The try catch on login always returns data undefined.

There is a method to catch errors generated upstream (400, the account does not exist, 401, credential invalid or another for an server error 404/500)?

Thanks

**Comment by Intevel** [comment]
There is currently no really good Error handling. I have to improve it.

**Comment by linkb15** [comment]
do you need help on that @Intevel .. I can learn on how to help this error since I also need it too

**Comment by linkb15** [comment]
#78 is adding a simple throw error for now.. since we need to access the `error.data`

```
const { login } = useDirectusAuth()

...

try {
  await login({ email: '', password: '' })
} catch (e) {
  console.log(e.data)
}
```

`e.data` will looks something like this
```
{
    "errors": [
        {
            "message": "Invalid user credentials.",
            "extensions": {
                "code": "INVALID_CREDENTIALS"
            }
        }
    ]
}
```

**Comment by Intevel** [comment]
This looks good. I will release it later.
